### PR TITLE
Apply unified code quality standards

### PR DESCRIPTION
**Pull request by remcohaszing**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

- Code is formatted using Prettier, except markdown files.
- JavaScript code is linted using XO.
- Markdown is checked using remark-preset-wooorm.
- GitHub actions is used to validate tests and code quality.
- No package-lock.json file is generated.
- Dependency version ranges of the form ^x.0.0 are used.

Many configurations have been copy-pasted from unified.

This is an initial step to start enhancing unified-language-server.

- A broken test has been skipped.
- Due to the synchronous nature, CJS is still used.
- TypeScript checks aren’t implemented yet.
- Code coverage hasn’t been implemented yet.

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]
Thanks @remcohaszing!

**Review by wooorm — APPROVED** [review]
Looks good. I didn’t check every line as it’s a lot and I assume it’s good. Do share if there’s anthing in particular that you want to be reviewed.

**Comment by remcohaszing** [comment]
I think the most important thing to review is that it still works.

I verified this manually by using it with [`vim-lsp`](https://github.com/prabirshrestha/vim-lsp) before and after these changes.

**Comment by wooorm** [comment]
I haven’t used this before, so I can’t help there, but :+1: on how you checked it

**Comment by wooorm** [comment]
Good to go I think?

**Comment by remcohaszing** [comment]
Yep, this is ready to go.

**Comment by wooorm** [comment]
Landed!

**Pull request merged**
